### ISSUE TITLE
website: links to go files in godoc are broken

### ISSUE THREAD

**Issue by mpl** [perkeep/perkeep#1036]
On e.g. https://perkeep.org/pkg/index , the link for receive.go is https://perkeep.org/pkg/receive.go , whereas it should be https://perkeep.org/pkg/index/receive.go

So it's basically missing the package name (or maybe just the last part of it, I haven't tried with longer import names).

I suspect it might be a regression from 101ce48bdcfa235d5cb9c815eec6baf333cfcb94 or 9787462d4989cf3c4c726fe7c8d2a72e5dfe73d4 but I haven't followed these CLs.

**Comment by mpl** [comment]
Leaving for @willnorris unless he tells me otherwise.

**Comment by willnorris** [comment]
looks like a relative path issue.  If you browse the godocs as https://perkeep.org/pkg/index/ (with a trailing slash), then the link works. I'm looking into it now.

**Comment by willnorris** [comment]
oddly, this works fine when I run the website locally.  @mpl: what arguments do we run the website with in production?  What path is it run from?  I suspect the code for that is checked in somewhere, I just don't remember where.

**Comment by willnorris** [comment]
never mind, I see it all now in camweb.go (prodSrcDir ad setProdFlags)

**Comment by willnorris** [comment]
okay, I think I'm on to something.  the page title at https://perkeep.org/pkg/index/ is `index (/pkg/index)` when in fact it should be `index (perkeep.org/pkg/index)`.  The `domainName` var isn't be set properly.  

It looks like that is because I'm setting it [in an `init` method](https://github.com/perkeep/perkeep/blob/990b613e2e4950227cb4bc17e5efe1be23360b84/website/godoc.go#L56).  I assumed that was safe since `*root` is a command line flag that should be set by this point in the code. However, in production, the `*root` var is actually set [in `setProdFlag`](https://github.com/perkeep/perkeep/blob/990b613e2e4950227cb4bc17e5efe1be23360b84/website/camweb.go#L631) which is called from `main`.  So I just need to initialize the domainName var after that.  Patch forthcoming.

**Comment by mpl** [comment]
ah sorry, i only saw your question now. yeah, all in camweb.go.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/13366
