### ISSUE TITLE
android uploader does not upload

### ISSUE THREAD

**Issue by comotion** [perkeep/perkeep#1049]
Hi,
being able to sync stuff off my smartfone and maybe replicate between servers is what inspired me to try out Perkeep.
I set up a simple internet-facing plain HTTP server with auth: userpass
The app just sits there and doesn't auto-upload anything, and when I do a sharing intent it looks like it starts for a split second before crashing.
I've sent feedback through the crash dialog but thought I'd log it here to perhaps get feedback myself.
I'm using Camlistore Uploader 0.6.1 on a Samsung Galaxy A3.

**Comment by mpl** [comment]
wait, there's a feedback dialog? you mean for Android devs, right? not for us Perkeep devs?

In any case, I would not be surprised that it does not work with a recent Perkeep server as we did a lot of breaking changes recently. What Perkeep version are you using? from git (what revision?), from a tarball, etc?

**Comment by comotion** [comment]
Using perkeep latest git here, with head being one of your commits from jan 25, 26925d41.
That feedback should reach Brad Fitzpatrick who uploaded the app to google play.
If that's the case, shouldn't the app show an error like "incorrect server api version, need <= 1.2" or something?
If there are breaking changes, which version should I use and expect the android app to work?

**Comment by mpl** [comment]
Oh, the app version on google play is extremely old, and I would not recommend using it. I don't know what server version would work with it. But if you have to, I guess you could build a server from a git revision from when the app was built, i.e. 2014 or a bit later.

I would advise to use a more recent build of the app, like https://storage.googleapis.com/camlistore-release/android/app-debug.apk , with a server version of sometime in 2017 (not later, because I think the most breaking changes happened in jan 2018). If that does not work, let me know and I'll try to bake another apk.

**Comment by edrex** [comment]
F-droid plz thx

**Comment by mpl** [comment]
Ah good idea. I'll see about pushing my next apks there.

**Comment by comotion** [comment]
Thanks, I will try compiling from december 2017 and install the apk you linked. However, wouldn't it make strong sense to update the google play app, or even better, submit a new Perkeep app and get that old one removed? As I understand it the name change coincides with you guys signalling that the code is getting ready for wider adotion, and offloading from the phone is one of those features that could get Joe Sixpack's nerdy daugher interested...

**Comment by mpl** [comment]
Sure it would, only I don't have any control over the publishing of the app on google play. @bradfitz  only does.

I suspect he will indeed at least make a new Perkeep google play page, or update the existing one.

But ill see about f-droid anyway, and if i can, ill keep an updated apk there.

Related: https://github.com/perkeep/perkeep/issues/981#issuecomment-350541434

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/14046

**Comment by comotion** [comment]
Downgrading to Dec 31st revision and using your APK worked for me, I can now share files from my phone. Auto-upload still doesn't do anything though. I see your commit that fixes newer revisions and might fix the auto-upload issue, perhaps due to permissions. I would be happy to pre-alpha test this if you can provide me with an apk.

**Comment by mpl** [comment]
@comotion glad to hear you have something half working for now.
The recent commit 19827cb591da16c0a13daf2e63c612504b167433 mainly focuses on updating (and fixing) our build process, and to make the app work with recent servers (Perkeep compiled at least at 6e8a5930c9fee81640c6c75a9a549fec98064186). So you should only use it if you want to go back to a very recent server version.
It may have made the auto-uploader situation a bit better, but I'm pretty sure it did not totally fix it. I've tried it and from what I understand it works only as long as the app stays in the foreground. And to be honest I don't understand yet how it ever was supposed to fully work before. Even if Android memory scheduler was less aggressive, there was always the possibility for it to kill the file watchers I think.

I'm currently working on fixing it properly but progress is slow, because well, it's Android and Java.

Anyway, if you still want an apk at rev 19827cb591da16c0a13daf2e63c612504b167433, I can build one for you oc (or you can build it yourself if you want, the build process itself is open-source).

**Comment by comotion** [comment]
The last release is from May 2017 so yes, I would like to use a more up-to-date Perkeep. I do not have an android toolchain set up and am hoping you can roll an apk for me instead. An autoupload that only works in the foreground is still pretty awesome as it makes it possible to upload all the photos without relying on the google cloud. The current situation is that "something" happens if autoupload is on and I plug in the charger, as the counters in the app are increasing, however no objects get stored in perkeep.

I'll file a new bug for this only if the same problem exists on newer revisions.

**Comment by mpl** [comment]
You don't the android toolchain to build it yourself, as we do it all in docker. See clients/android/Makefile. Anyway, here's a recent build: https://storage.googleapis.com/camlistore-release/android/app-debug-dff0bb4ad5.apk but as I said, the auto-uploader does not really work any better there.

Please do not open another issue. I'm already working on the auto-uploader, and I'm using this issue here to track progress. I made good progress yesterday and I'm fairly confident I'll have a new commit for it soon.

**Comment by comotion** [comment]
ok cool. I'll update my perkeep and will be ready to track your changes.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/14186

**Comment by mpl** [comment]
@comotion In case you want to alpha-test it, here's an apk I built from the solution I propose in the above CL: https://storage.googleapis.com/camlistore-release/android/app-debug-14186.apk

**Comment by comotion** [comment]
@mpl the 14186 app keeps crashing on startup

**Comment by mpl** [comment]
@comotion Could you provide the logs please, so I can try to debug?

adb logcat
start the app
interrupt adb logcat

**Comment by mpl** [comment]
@comotion if you can't share logs, could you please at least share other relevant info such as phone model and android version, so I can try to reproduce your crash in an emulator?

**Comment by comotion** [comment]
[camlistore-clean.log](https://github.com/perkeep/perkeep/files/1775392/camlistore-clean.log)

**Comment by mpl** [comment]
@comotion excellent, thank you.

**Comment by mpl** [comment]
yeah ok, android.app.NotificationChannel was introduced in API level 26, which apparently means Android 8.0 , which is indeed a bit harsh of a requirement. I'll have to find another way.

**Comment by mpl** [comment]
@comotion I've updated the CL to use some lower API code, and I've built this new apk with it:
https://storage.googleapis.com/camlistore-release/android/app-debug-14186.apk
Can you please try it?

**Comment by comotion** [comment]
OK, the new app does not crash, and can share-intent upload to master HEAD. Yay!

Auto-upload still does nothing though. "Running UploadThread" starts only if I plug in power - regardless of AutoUploader setting, and although mem_alloc and mem_heap_released changes over time 0 bytes are ever uploaded. Hitting PAUSE / RESUME does nothing. Menu item "Upload All" does nothing, and "Stop" exits the upload thread which does not upload anything.

**Comment by comotion** [comment]
[perkeep.log](https://github.com/perkeep/perkeep/files/1780714/perkeep.log)
log for attempted autoupload

**Comment by mpl** [comment]
@comotion first of all, I'm not certain any of the "only on wifi", "only on power", etc options work properly (I have not touched them yet, because how they were supposed to work puzzled me when I read the code), so it's best to try with them all disabled for now.

Second, your log is weird, because I don't see it showing anywhere that you took a photo. So, just to be sure, is this what you tried?
1)  enable auto-upload in perkeep settings
2) in auto-upload settings, tick "Photos (DCIM/Camera)"
3) go to the camera app, and take a picture

Third, before trying anything, let's make sure your app is not in a weird state by killing it completely:
adb shell am force-stop org.camlistore
should do it. Then launch the app again.

**Comment by comotion** [comment]
Ok, disabling the two auto-upload options. Auto-upload and Photos all enabled.

I didn't take a picture in the previous log, because I expect "Upload all" to upload everything in the indicated folders and not just wait for new content. Is that the wrong assumption? In any case, I have taken pictures while the auto-uploader runs without these getting uploaded - just not in that log.

Third, here's a log after having configured the app and force-stopped>
[perkeep-autoupload.log](https://github.com/perkeep/perkeep/files/1784714/perkeep-autoupload.log)
0. adb shell am force-stop org.camlistore && adb logcat -c && adb logcat > perkeep-autoupload.log
1. start camlistore uploader
2. switch to camera & take a picture
3. check if anything happened in camlistore uploader (Still says Idle)
4. stop the logcat

I can get it out of idle and into "Uploading..." by re-plugging the USB connection, but still no files are being uploaded.

**Comment by mpl** [comment]
> I didn't take a picture in the previous log, because I expect "Upload all" to upload everything in the indicated folders and not just wait for new content. Is that the wrong assumption?

It is correct that "Upload all" should upload all your photos. However it is not the same feature as the auto-uploader, and they don't correspond exactly to the same code path either. So it could very well be that "upload all" works and the auto-uploader does not, or vice-versa. And since we're currently debugging the auto-uploader I did not want to confuse the issues.

Anyway, i'll have a look at the log, thanks.

**Comment by mpl** [comment]
@comotion I found something suspicious in your log, which could explain why both "upload all" and the auto-uploader don't work, so that's good news. I've added some more debugging statements in https://storage.googleapis.com/camlistore-release/android/app-debug-14186.apk to help confirm the suspicion.

Can you please retry (either upload all or auto uploading) with it and resend logs?

**Comment by comotion** [comment]
Good thinking, they are separate problems but maybe the underlying cause is the same?
Glad you are making headway. I would love for both things to work of course.

Here is a log of upload all:
[perkeep-uploadall.log](https://github.com/perkeep/perkeep/files/1788944/perkeep-uploadall.log)

and here is a log of auto-upload (start app, switch to camera, take picture, switch back..)
[perkeep-autoupload.log](https://github.com/perkeep/perkeep/files/1788945/perkeep-autoupload.log)

**Comment by mpl** [comment]
@comotion perfect, at least for uploadall it is as I suspected: the app does not find any photos because the usual directories (such as /storage/emulated/0/DCIM/Camera) it is looking in do not seem to exist.

Now we have to figure out why. I would guess that the "external sd card" root (/storage/emulated/0) is somehow different on your phone. Can you tell me if you have a "DCIM/Camera" directory, or even just "DCIM", somewhere? if yes, can you give me its full path?

**Comment by comotion** [comment]
`/storage/emulated/0/` is internal storage, and aliases `/storage/self/primary`. So, `/storage/emulated/0/DCIM/Camera` does exist but is empty as I use the microsd card for photos.
I can't tell what else is under /storage/emulated as the fone is not rooted and the read bit is lacking on that directory.

Looks like external SD card is under `/storage/0123-4567/`
and does indeed have `DCIM/Camera`

I see there exists a way to get external storage without hard-coded paths: https://stackoverflow.com/questions/22404750/common-storage-path-for-all-android-devices#22405373

**Comment by mpl** [comment]
> I see there exists a way to get external storage without hard-coded paths: https://stackoverflow.com/questions/22404750/common-storage-path-for-all-android-devices#22405373

Yes, that is exactly what we use, but that gives /storage/emulated/0/ . So now I have to figure out how to get your actual external external SD card, which might be emulated at /storage/emulated/1/. I was asking you for the path to see if something weird was going on. I'll look into it.

**Comment by comotion** [comment]
There is no path at `/storage/emulated/1/` - I checked in the shell.

**Comment by mpl** [comment]
@comotion Could you please retry with the new https://storage.googleapis.com/camlistore-release/android/app-debug-14186.apk I've just uploaded please?

Sorry to make you go through these hoops, but as I don't have an external sd storage slot on my phone, there's no way for me to try that this code works for sure.

**Comment by comotion** [comment]
Success! :1st_place_medal: 
Auto-upload works, and immediately sends captured images to Perkeep, and 
Upload-All works, happily slurping all my photos from the sd card to Perkeep.
:+1:

**Comment by mpl** [comment]
Brilliant. Thank you for your patience.

**Comment by comotion** [comment]
And thank you for your patience @mpl.
Your fixes to the uploader app enable me to use Perkeep in exactly the way I was looking to use it: as a better replacement for centralized cloud providers. Seeing my 2000+ pictures stream into the UI is impressive.

**Comment by cliveb** [comment]
@mpl <https://github.com/mpl> thank you for polishing the uploader app. I
enjoy showing CS students and GDG communities how Perkeep is a well run
open source project to learn from. Brad's and your continuing efforts
combined together with many other contributors here showcase invaluable best
practices to learn from.

**Comment by mpl** [comment]
Cool. thanks for the spreading the good word about Perkeep.
