### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jpvlsmv** [perkeep/perkeep#1307]
It has been 2 years since the last official release, and there have been over 200 commits to master since 0.10.

There has been some drift between the documentation and the functionality a user gets from downloading the 0.10 version, what would it take to publish 0.10.2 (a milestone exists, just waiting for a fixed bug to be closed) or 0.11 just to bring us into the new decade?

**Comment by mpl** [comment]
We usually try to cut a release so that it includes a specific new feature, and (incidentally) around a hacking event/gathering of some kind. And since we've slowed down on both it kind of explains why we haven't cut any new one.
That said, I don't see any obstacle that would prevent us from baking one, so I suppose we could.
@bradfitz , WDYT?

**Comment by roopakv** [comment]
friendly ping. on the brew side this formula remains broken and would be nice to get it building or maybe potentially remove it from brew if it cant be fixed

cc @bradfitz for thoughts

**Comment by GTP95** [comment]
I'll add my unrequested two cents. I think it would be important for the project to release a new official release because there are potential users that assume the development is stalled because they didn't see a new version in two years, eg. here: [https://www.reddit.com/r/DataHoarder/comments/hijitn/perkeep_permanently_keep_your_stuff_for_life/fwgjvh4?utm_source=share&utm_medium=web2x](url)
The new release doesn't need to have any special new feature, just set it as a commit that works and announce the new release on the website. 
Then stop implementing new functionalities for a while (doesn't need to be a long time, maybe just a couple of months is enough) and move on to fix some of the usability issues mentioned in #1244: to me, it makes little sense to implement new things while most users struggle to use what's already there. Most of them are UI issues that would take little time to fix but would greatly improve the user's perception of this project. Having some (little) side projects myself I've often (always?) followed the approach "implement the hard stuff first, polish things later", only to find out that, since usually the hard stuff is also the most interesting part of the project, once I've implemented it I lose interest and never go on to the polish part, because it's boring. This is ok for side projects, but if you wish Perkeep to be something more than your own project you need to do also the boring part. In this regard, having a new release could attract more users and maybe some new developers that could help to improve the interface, and this, in turn, would attract more users. I would contribute myself if I knew go, but sooner or later I think I'll learn it and I might get in touch to contribute.
I think that for this project the potential is there, but a lot of users that see it for the first time may have the feeling that it's not at the point where it should be after years of development. This perception can be greatly changed by UI and docs improvements as suggested in #1244, so in my humble opinion investing the next two/three months in UI and docs will worth it in the long run.

**Comment by joelzanden** [comment]
Thank you, @GTP95! Very well put!
I am one of those interested users/developers. I keep coming back to check in on the Perkeep project and I keep not diving in because of exactly what you just wrote.

**Comment by Kyrluckechuck** [comment]
Just wanted to chime in to say I'm a potential user who is in the same boat -- I saw the last release was in 2018 and I immediately went to ignore this, but then found the GitHub project and realized it had a merge in the last 2 months so it's not _completely_ dead. 

Most users, however, won't do that and even if they are minor bug fixes getting released as sub-versions (which is what most projects are doing these days), it would project a much stronger/stable image to the community that development is ongoing, potentially even interesting more developers to help contribute.

**Comment by bradfitz** [comment]
@mpl, if you want to roll a release, SGTM.

**Comment by mpl** [comment]
ACK, will try/do.

**Comment by willnorris** [comment]
I'd also be happy to learn how, so that it doesn't always fall on you.

**Comment by GTP95** [comment]
Great to see that finally something is moving! I've since moved on to use Nextcloud, but I will for sure come back in the future to check how things are going, especially regarding the ability to share files with other people and to reserve some space to let others have an encrypted backup of their instance.
