### ISSUE TITLE
importer: gphotos importer will stop working soon

### ISSUE THREAD

**Issue by bradfitz** [perkeep/perkeep#987]
https://developers.google.com/drive/v3/reference/ currently says:

> The photos space will sunset in early January 2018. Your users can continue to access Google Photos via the drive space by enabling the Google Photos folder in My Drive in the Drive client settings

I assume that's referring to this part of the API it looks like we currently use:

```go
                        r, err = dl.Service.Changes.List(token).
                                Context(ctx).
                                Fields("nextPageToken,newStartPageToken, changes(file(" + fields + "))").
                                Spaces("photos").
                                PageSize(batchSize).
                                RestrictToMyDrive(true).
                                IncludeRemoved(false).Do()
```

Note that `Spaces("photos")` part.

I'll fix.

/cc @mpl @tgulacsi

**Comment by mpl** [comment]
oh. I thought _both_ - enabling the Photos folder in Drive, _and_ using the "photos" Space in the API calls - were necessary. I already have the folder enabled (since the user level docs say we have to), and I had never tried the importer without it.

So what, we're going to use the "drive" Space instead, but then I'm not sure how we're going to filter out anything that is not from the Google Photos "folder". I suppose even though Drive is all flat, the folder name must be somewhere...

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/14766

**Comment by flexd** [comment]
hey, found Perkeep again today via HN! Sorry for necroing this old issue, but I think it's finally broken now.
I don't think it's possible to enable the photos folder in Drive anymore. I can't find any option to do so, unfortunately.
It appears that was disabled in 2019 https://blog.google/products/photos/simplifying-google-photos-and-google-drive/

> Any photos or videos from Drive in Photos that you have uploaded prior to this change will remain in Photos. If you have a “Google Photos” folder in Drive, it will remain in Drive, but will no longer update automatically. 

the importer ran happily, but no pictures ended up getting imported.
